// resources/views/inertia/react/components/TextInput.jsx
import { forwardRef } from 'react';

const TextInput = forwardRef(function TextInput(
    { type = 'text', className = '', isFocused = false, ...props },
    ref
) {
    return (
        <input
            {...props}
            type={type}
            className={`rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 mt-1 block w-full ${className}`}
            ref={ref}
        />
    );
});

export default TextInput;

// resources/views/inertia/vue/components/TextInput.vue
<script setup>
defineProps({
    value: String,
    modelValue: [String, Number, Boolean],
});

defineEmits(['update:modelValue']);
</script>

<template>
    <input
        :value="modelValue"
        @input="$emit('update:modelValue', $event.target.value)"
        class="rounded-md border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 mt-1 block w-full"
    />
</template>
